# Generated by Django 5.2.4 on 2025-08-06 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0010_room_ac_type_alter_room_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAndDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('food_item', models.CharField(max_length=100)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('drink_item', models.CharField(max_length=100)),
                ('drink_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
