# Generated by Django 5.2.4 on 2025-08-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_checkin_date_and_more'),
        ('foods', '0002_alter_foodanddrink_drink_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodanddrink',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='foodanddrink',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
