# Generated by Django 5.2.4 on 2025-08-12 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_checkin_datetime'),
        ('foods', '0003_foodanddrink_booking_alter_foodanddrink_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodanddrink',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
            preserve_default=False,
        ),
    ]
