# Generated by Django 5.2.4 on 2025-07-24 06:20

import django.db.models.deletion
import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomtype_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(default=rooms.models.get_default_floor, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.floor'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='floor',
            field=models.ForeignKey(blank=True, default=rooms.models.get_default_floor, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.floor'),
        ),
    ]
