# Generated by Django 5.2.4 on 2025-07-24 06:57

import django.db.models.deletion
import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_floor_alter_roomtype_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='floor',
            field=models.ForeignKey(default=rooms.models.get_default_floor, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.floor'),
        ),
    ]
