# Generated by Django 5.2.4 on 2025-07-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_status_alter_roomtype_base_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='amenities',
            field=models.TextField(blank=True, default='No amenities listed'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, default=[]),
            preserve_default=False,
        ),
    ]
