# Generated by Django 5.2.4 on 2025-07-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_roomtype_amenities_alter_roomtype_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='floor',
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='amenities',
            field=models.TextField(blank=True),
        ),
    ]
