# Generated by Django 5.2.4 on 2025-07-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_roomtype_floor_alter_roomtype_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='ac_type',
            field=models.CharField(choices=[('ac', 'A/C'), ('non-ac', 'Non A/C')], default='non-ac', max_length=10),
        ),
    ]
