# Generated by Django 5.2.4 on 2025-08-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_remove_roomtype_base_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('AC', 'A/C'), ('Non-AC', 'Non A/C')], max_length=10),
        ),
        migrations.RenameField(
            model_name='room',
            old_name='rate_per_night',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
