# Generated by Django 5.2.4 on 2025-08-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_room_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ac_type',
            field=models.CharField(choices=[('AC', 'A/C'), ('Non-AC', 'Non A/C')], default='Non-AC', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite')], max_length=20),
        ),
    ]
