# Generated by Django 5.2.4 on 2025-08-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_room_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor__number', 'room_number']},
        ),
        migrations.AlterField(
            model_name='room',
            name='ac_type',
            field=models.CharField(choices=[('ac', 'A/C'), ('non-ac', 'Non A/C')], default='non-ac', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
