# Generated by Django 5.2.4 on 2025-08-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_alter_floor_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterField(
            model_name='room',
            name='ac_type',
            field=models.CharField(choices=[('AC', 'A/C'), ('Non-AC', 'Non A/C')], default='Non-AC', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.floor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
    ]
