# Generated by Django 5.2.4 on 2025-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
