# Generated by Django 5.2.4 on 2025-08-10 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='booking',
            name='document_type',
            field=models.CharField(choices=[('Aadhar', 'Aadhar'), ('License', 'License'), ('PAN', 'PAN')], default='Aadhar', max_length=50),
        ),
    ]
