# Generated by Django 5.2.4 on 2025-08-12 04:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkout_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_datetime',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pre_booked', 'Pre Booked'), ('booked', 'Booked')], default='pre_booked', max_length=20),
        ),
    ]
