# Generated by Django 5.2.4 on 2025-08-12 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_id_alter_booking_checkin_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
