# Generated by Django 5.2.4 on 2025-08-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed')], default='booked', max_length=20),
        ),
    ]
