# Generated by Django 5.2.4 on 2025-08-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_booking_booking_type_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_type',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('pre-booked', 'Pre-Booked')], default='booked', max_length=20),
        ),
    ]
