# Generated by Django 5.2.4 on 2025-08-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_remove_booking_booking_type_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('pre-booked', 'Pre-Booked'), ('completed', 'Completed')], default='booked', max_length=20),
        ),
    ]
