# Generated by Django 5.2.4 on 2025-08-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_booking_invoice_number_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('pre-booked', 'Pre-Booked')], default='booked', max_length=20),
        ),
    ]
