# Generated by Django 5.2.4 on 2025-08-06 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_booking_status_booking_status'),
        ('checkin_checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='members',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='room',
        ),
        migrations.AddField(
            model_name='checkin',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
