# Generated by Django 5.2.4 on 2025-08-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_checkin_date_and_more'),
        ('checkin_checkout', '0002_remove_checkin_check_in_remove_checkin_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
