# Generated by Django 5.2.4 on 2025-08-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0003_alter_checkin_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='checkout_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
