# Generated by Django 5.2.4 on 2025-08-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0004_checkin_checkout_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='checkout_datetime',
        ),
    ]
